### ISSUE TITLE
Windows font

### ISSUE THREAD

**Issue by kobuworks** [yas-sim/handwritten-japanese-ocr#1]
Hi yas-sim,
Thanks a lot for sharing great code!!!
FYI, for Windows,  fontName = 'msgothic.ttc' worked at my Win10 env., fontName = 'meiryo.ttc' did not work, though I could not reach the route cause.
Thanks,
BR/Kobu

**Comment by yas-sim** [comment]
Thank you Kobu-san.

I have switched the font for Win10 from meiryo.ttc to msgothic.ttc because the msgothic.ttc is more popular and common in Japanese Win10 environment. I believe it's safer than using meiryo.ttc.

Please pull the code again and confirm if the change is reflected and working.

Thanks

**Comment by kobuworks** [comment]
Hi yas-sim san,
git cloned the new code on Win10, worked. ;-)
Thanks a lot!!
BR/Kobu
![rainy-day](https://user-images.githubusercontent.com/56861258/81019190-161b7b00-8ea1-11ea-8719-10dac00fff49.png)

**Comment by yas-sim** [comment]
issue resolved. closed.
